//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Seawolf8Simulation
{
    [Serializable]
    public class OverrideRCInMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/OverrideRCIn";
        public override string RosMessageName => k_RosMessageName;

        //  Override RC Input
        //  Currently MAVLink defines override for 18 channels
        //  https://mavlink.io/en/messages/common.html#RC_CHANNELS_OVERRIDE
        public const ushort CHAN_RELEASE = 0;
        public const ushort CHAN_NOCHANGE = 65535;
        public ushort[] channels;

        public OverrideRCInMsg()
        {
            this.channels = new ushort[18];
        }

        public OverrideRCInMsg(ushort[] channels)
        {
            this.channels = channels;
        }

        public static OverrideRCInMsg Deserialize(MessageDeserializer deserializer) => new OverrideRCInMsg(deserializer);

        private OverrideRCInMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.channels, sizeof(ushort), 18);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.channels);
        }

        public override string ToString()
        {
            return "OverrideRCInMsg: " +
            "\nchannels: " + System.String.Join(", ", channels.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
